image: r-base:3.3.0

before_script:
  - apt-get update -qq && apt-get install -y -qq r-base-dev

build:
  script:
    - R CMD devtools::document(roclets=c('rd', 'collate', 'namespace'))
    - R CMD devtools::build()

